# Generated by Django 4.2 on 2023-04-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watched', '0002_alter_watched_rating_alter_watched_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='watched',
            name='movie_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
