# Generated by Django 4.2 on 2023-04-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='to_watch',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
