# Generated by Django 4.2 on 2023-04-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_watch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_watch',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
