# Generated by Django 4.2 on 2023-04-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_watch', '0002_to_watch_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_watch',
            name='movie_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
